#Para desarrollo local ( localhost, root)

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password:  ${DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update # Modifica el schema para que coincida, sin borrar datos. En 'none' no toca el schema.
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: never # Para que no ejecute el script de schema.sql. En 'always' siempre ejecuta el script al iniciar.
      schema-locations: classpath:schema.sql
