#Para desarrollo local ( localhost, root)

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password:  ${DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: never # cambiar a always
      schema-locations: classpath:schema.sql
